name: Release
on:
  push:
    branches:
      - master

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  ghp:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js for GHP
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"

      - name: Prep artifact for github package publishing
        run: |
          npm install -g json
          json -I -f package.json -e 'this.publishConfig.registry="https://npm.pkg.github.com/"'
          TAG="$(git describe --tags)"
          TAG=${TAG:1}
          json -I -f package.json -e 'this.version="'$TAG'"'

      - name: Publish to GHP
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm publish
